# Generated by Django 4.1.7 on 2023-03-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='user',
            name='is_manager1',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
