# Generated by Django 4.1.7 on 2023-03-09 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='upload/')),
            ],
            options={
                'db_table': 'addfile',
            },
        ),
    ]
